name: earthdaily
channels:
 - conda-forge
 - defaults
dependencies:
 - numpy
 - python>=3.10
 - gdal>=3.7.0
 - pandas>=2
 - geopandas>=0.11
 - rasterio
 - pystac-client
 - requests
 - matplotlib
 - xarray
 - rioxarray
 - h5netcdf 
 - pystac
 - odc-stac>=0.3.7
 - tqdm
 - joblib
 - python-dotenv
