name: earthdaily
channels:
 - conda-forge
 - defaults
dependencies:
- numpy
- scipy
- matplotlib
- joblib
- psutil
- pystac-client
- pystac
- odc-stac>=0.3.7
- pandas>=2
- geopandas
- requests
- xarray
- rasterio
- rioxarray
- tqdm
- python-dotenv
- rich
- dask
- dask-image
- spyndex