name: ruff

on:
  push:
    branches:
        - dev
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nkarasiak/ruff-action@v2.1
      with:
        src: "./earthdaily"
        args: --ignore F401,E722
    - uses: nkarasiak/ruff-action@v2.1
      with:
        src: "./earthdaily"
        args: format
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'style(ruff) : automatic lint/format'